# 服务器配置
ServerConfig:
  host: 0.0.0.0  # 主机
  port: 6868  # 端口
  workers: 1  # 进程数
  token_expire: 604800  # Token有效期（秒），用户登录有效期
  verification_code_expire: 300  # 验证码有效期（秒）
  file_max_size: 3145728  # 文件最大上传大小（字节）
  super_admin_username: admin  # 默认超级管理员用户名
  super_admin_password: admin  # 默认超级管理员密码

# 数据库配置
DatabaseConfig:
  # Mysql配置
  MysqlConfig:
    host: 127.0.0.1  # 主机
    port: 3306  # 端口
    database_name: admin_system  # 数据库名称
    username: root  # 用户名
    password: root  # 密码

  # Sqlalchemy配置
  SqlalchemyConfig:
    on_echo: false  # 是否开启查询日志

  # Redis配置
  RedisConfig:
    host: 127.0.0.1  # 主机
    port: 6379  # 端口
    password: '' # 密码
    db: 9  # 数据库